package com.example.demo.mapper;

import com.example.demo.model.Class;

public interface ClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Wed Jan 12 23:46:19 CST 2022
     */
    int insert(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Wed Jan 12 23:46:19 CST 2022
     */
    int insertSelective(Class record);
}