package com.example.demo.mapper;

import com.example.demo.model.Student;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed Jan 12 23:52:02 CST 2022
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed Jan 12 23:52:02 CST 2022
     */
    int insertSelective(Student record);

    Student queryInfoById(Integer id);
}